### ISSUE TITLE
[FE] 타이머 시작 관련 기능 추가 제안

### ISSUE THREAD

**Issue by MoonJeWoong** [woowacourse-teams/2023-haru-study#263]
## 제안 배경
- 서비스 이용 중 타이머를 누르고 시작을 해야하는데 계속 까먹게 되네요... 계획이나 회고 진행 시 사용자가 텍스트 입력 창을 클릭했을 때 타이머도 같이 시작되도록 하면 어떨까요?

## 추가할 기능
- [ ] 사용자가 텍스트를 입력하기 위해 클릭을 하는 순간 타이머도 같이 시작되도록 하는 기능

**Comment by nlom0218** [comment]
타이머가 시작하지 않다면 답변을 입력할 수 없다거나 시작버튼에 애니메이션을 주어 클릭하라는 것을 명시하거나 등등! 방장기능을 도입할 때 함께 고민해봐요 :)

**Comment by woo-jk** [comment]
타이머에 관한 UI/UX 개편이 이루어져야 할 것 같아요. 히이로나 노아가 말한 방식 포함해서 다같이 의논해봅시다~!
