### ISSUE TITLE
[FE] 브라우저 탭 창에서 타이머를 보여주는 기능

### ISSUE THREAD

**Issue by MoonJeWoong** [woowacourse-teams/2023-haru-study#264]
## 제안 배경
현재는 브라우저에서 하루스터디 서비스 창을 띄워두고 다른 탭에서 작업을 하는 경우 타이머 시간을 바로바로 확인을 할 수 없어 불편합니다. (하루스터디 명예 QA 허브에게 받은 피드백이에요😄)

## 추가할 기능
- [ ] 브라우저 탭에서도 타이머를 확인하는 기능

## 참고하면 좋을 것 같은 레퍼런스
- https://vclock.kr/%ED%83%80%EC%9D%B4%EB%A8%B8-3-%EC%B4%88/

**Comment by nlom0218** [comment]
맞아요 해당 기능 추가되면 좋을거 같아요! 추가적으로 데모때 받은 피드백을 바탕으로 시간이 종료되면 알림을 들려주는 것도 고려해보죠!

**Comment by woo-jk** [comment]
저도 이 기능은 생각 중이었어요! 추가를 고려해보겠습니다.

**Comment by woo-jk** [comment]
#535
