### ISSUE TITLE
[ALL/FE/BE] 시간이 다 지나면 이상하게 나오는 버그

### ISSUE THREAD

**Issue by drunkenhw** [woowacourse-teams/2023-haru-study#278]
## 버그 기능
- 버그가 발생하는 페이지나 기능을 설명합니다.
시간이 다 되니깐 -1:-1이라고 뜹니다
### 버그 재연 방법
- 어떤 상황에서 버그가 발생하는지 설명합니다.
<img width="532" alt="image" src="https://github.com/woowacourse-teams/2023-haru-study/assets/106640954/3a93d979-bd33-4e9c-a8e0-ec65ecd4bad3">

### 기대 동작
- 원래 기대하던 정상 동작에 대해 설명합니다.

### 현재 동작
- 기대와 다른 현재의 동작에 대해 설명합니다.

**Comment by jaehee329** [comment]
감사합니다~
다음 이슈와 유사해서 이후에 함께 해결로 처리할게요
ref #269
