### ISSUE TITLE
[BE] study 생성시 글자수 제한이 넘어가면 500이 돌아옵니다

### ISSUE THREAD

**Issue by be-student** [woowacourse-teams/2023-haru-study#280]
## 버그 기능
- 버그가 발생하는 페이지나 기능을 설명합니다.
POST https://haru-study.com/api/studies
{
    "name": "asdfasdfasdfasdfsdaf",
    "timePerCycle":"20",
    "totalCycle":"2"
}
### 버그 재연 방법
- 어떤 상황에서 버그가 발생하는지 설명합니다.

postman 으로 데이터를 넣으면 500이 돌아옵니다

### 기대 동작
- 원래 기대하던 정상 동작에 대해 설명합니다.

400 코드로 응답

### 현재 동작
- 기대와 다른 현재의 동작에 대해 설명합니다.

500 으로 응답

**Comment by woosung1223** [comment]
#267 로 해결 완료했습니다 🙂
