### ISSUE TITLE
[BE] progress의 isDone 상태 추출 고려

### ISSUE THREAD

**Issue by woosung1223** [woowacourse-teams/2023-haru-study#382]
## 추가할 기능
- [ ] progress의 isDone 상태 추출을 고려한다.

- 기존
```
{
  ...
  step: done
  ...
}
```

- 제안
```
{
  ...
  step: retrospect,
  isDone: true
  ...
}
```

**Comment by jaehee329** [comment]
8.31회의에서 상태를 progress가 아닌 room 단위로 관리하며
room의 스터디 스테이지(?)는 default, planning, studying, retrospect로,
스터디의 전반적인 상태는 별도의 컬럼으로 waiting, running(?), done 구분하기로 결정함
