### ISSUE TITLE
[ALL]  API 명세서 초안 검토

### ISSUE THREAD

**Issue by MoonJeWoong** [woowacourse-teams/2023-haru-study#50]
## 검토사항
- [x] URI 검토
- [x] JSON 데이터 명 검토
- [x] 예외상황 처리를 위한 API 양식 명세
  - [x] 예외상황에 따른 예외코드 명세서 작성 방법 정하기
  - [x] JSON 양식 결정하기
    - 에러코드만 반환할 지?
    - 에러코드 + 설명도 반환할 지?

**Comment by jaehee329** [comment]
### API 명세
[Wiki](https://github.com/woowacourse-teams/2023-haru-study/wiki/MVP-API-%EB%AA%85%EC%84%B8%EC%84%9C) 에 정리해서 올렸습니다~

### 에러코드 관련
[여기](https://developers.kakao.com/docs/latest/ko/reference/rest-api-reference)와 같은 형식으로 작성하기로 하였으며 아래와 같은 형태로 응답할 예정입니다.
``` JSON
HTTP/1.1 400 Bad Request  
{
  "code" : -10,
  "msg" : "error message"
}
```

문제상황 별 에러코드는 도메인 별로 구분만 하였으며 세부적인 에러에 대해서는 개발을 진행하며 정의할 예정입니다.
