### ISSUE TITLE
[BE] DB 스키마 변경에 따른 엔티티 설계 변경

### ISSUE THREAD

**Issue by woosung1223** [woowacourse-teams/2023-haru-study#76]
## 추가할 기능
- [ ] 엔티티 설계를 변경한다.

- 참고 #75

**Comment by aak2075** [comment]
## 컨벤션

- 엔티티 기본 생성자 protected는 롬복의 @NoargsConstructor를 이용한다.
- 애너테이션의 속성 설정은 줄일 수 있으면 줄인다.
- 애너테이션 선언 순서는 추후 논의후 정리하기.
